name             "vimrc"
maintainer       "Allan Espinosa"
maintainer_email "allan.espinosa@outlook.com"
license          "Apache 2.0"
description      "Installs/Configures vimrc"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"
depends          "git", "~> 1.4.8"
depends          "vim", "~> 1.0.2"
recipe           "vimrc", "Downloads .vim and corresponding bundles"
